### ISSUE TITLE
Wrong password still returned successful job

### ISSUE THREAD

**Issue by lrochette** [electriccommunity/EC-ShareFile#1]
The call returned:
Workspace File  /   createFolderAndUploa.37215799-d7b2-11e4-8db3-22000b1d8c94.log  
More
122 : Username or Password was incorrect.

but the job was green
Check jobId 33f063b9-d7b2-11e4-aed5-22000b1d8c94

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-ShareFile#1
